FROM node:18-alpine as build

WORKDIR /build

COPY package.json ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build --declaration false

FROM node:18-alpine as main

WORKDIR /fleetkit

COPY --from=build /build/node_modules /fleetkit/node_modules
COPY --from=build /build/package.json /fleetkit/package.json
COPY --from=build /build/dist /fleetkit/dist
COPY --from=build /build/www /fleetkit/dist/www

RUN mkdir dist/data

EXPOSE 3000
CMD [ "node", "." ]